name: License Zero
description: gainful software in the open
url: https://blog.licensezero.com
permalink: :year/:month/:day/:title.html
author: Artless Devices LLC
homepage: https://licensezero.com
highlighter: rouge
excerpt_separator: "<!--jump-->"
repository: licensezero/licensezero-blog
repository_url: "https://github.com/licensezero/licensezero-blog"
plugins:
- jekyll-sass-converter
- jekyll-feed
exclude:
- vendor
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
