title: License Zero
description: gainful open software development
url: https://blog.licensezero.com
permalink: :year/:month/:day/:title.html
author: Artless Devices LLC
homepage: https://licensezero.com
highlighter: rouge
repository: licensezero/blog.licensezero.com
repository_url: https://github.com/licensezero/blog.licensezero.com
plugins:
- jekyll-sass-converter
- jekyll-feed
- jekyll-redirect-from
exclude:
- vendor
feed:
  path: feed.xml
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
